import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import mongoose from 'mongoose';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';
import userRoutes from './routes/users';
import sessionRoutes from './routes/sessions';
import analyticsRoutes from './routes/analytics';
import { asyncHandler, errorHandler } from './middleware/errorHandler';
import { authMiddleware, RequiredUserRequest } from './middleware/auth';
dotenv.config();
const app = express();
const PORT = process.env.PORT || 5000;
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/cardioflow';
app.use(cors({origin: [process.env.FRONTEND_URL || 'http://localhost:3000', 'http://localhost:19006'], credentials: true, methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], allowedHeaders: ['Content-Type', 'Authorization']}));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ limit: '10mb', extended: true }));
mongoose.connect(MONGODB_URI, {retryWrites: true, writeConcern: { w: 'majority' }}).then(() => console.log('✅ MongoDB connecté')).catch(err => console.error('❌ Erreur MongoDB:', err));
app.post('/api/auth/register', asyncHandler(async (req, res) => {const { email, password, firstName, lastName } = req.body; if (!email || !password) return res.status(400).json({ error: 'Email et mot de passe requis' }); const hashedPassword = await bcrypt.hash(password, 10); const user = { email: email.toLowerCase(), passwordHash: hashedPassword, firstName: firstName || '', lastName: lastName || '' }; const token = jwt.sign({id: user.email, email: user.email}, process.env.JWT_SECRET || 'secret_dev', { expiresIn: '30d' }); res.status(201).json({success: true, token, user: { email: user.email, firstName, lastName }}); }));
app.post('/api/auth/login', asyncHandler(async (req, res) => {const { email, password } = req.body; if (!email || !password) return res.status(400).json({ error: 'Email et mot de passe requis' }); const token = jwt.sign({id: email, email: email}, process.env.JWT_SECRET || 'secret_dev', { expiresIn: '30d' }); res.json({success: true, token, user: {email: email}}); }));
app.use('/api/users', authMiddleware, userRoutes);
app.use('/api/sessions', authMiddleware, sessionRoutes);
app.use('/api/analytics', authMiddleware, analyticsRoutes);
app.get('/health', (req, res) => {res.json({status: 'CardioFlow API running', timestamp: new Date().toISOString()}); });
app.use((req, res) => {res.status(404).json({ error: 'Route non trouvée' }); });
app.use(errorHandler);
app.listen(PORT, () => {console.log(`🫀 CardioFlow API running on port ${PORT}`); });
export default app;